# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  workflow_call:

#  push:
#    branches: [ "main" ]
#    paths:
#      - 'ui/vite-ui-app/**'
#  pull_request:
#    branches: [ "main" ]

jobs:

  containerise:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: EKS Deploy Prep
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Let's set the env var so all kubectl commands know where the kubeconfig is
        export KUBECONFIG=$PWD/kubeconfig
        aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --no-verify-ssl
        ls -al
        kubectl get svc

    - name: Deploy to EKS
      run: |
        ls -al
