name: parent

on:
  push:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest

    # Set job outputs to values from filter step
    outputs:
      ui-api: ${{ steps.filter.outputs.ui-api }}
      ui-app: ${{ steps.filter.outputs.ui-app }}

    steps:
    - uses: actions/checkout@v4
    - run: ls -al
    - run: ls -al .github/workflows

    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ui-api:
            - 'ui/ui-api/**'
          ui-app:
            - 'ui/vite-ui-app/**'

  ui-api-job:
    needs: changes
    if: ${{ needs.changes.outputs.ui-api == 'true' }}
    uses: ./.github/workflows/ui-api.yml

#  ui-api-job:
#    runs-on: ubuntu-latest
#    needs: changes

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

#      - name: Build UI API?
#        if: ${{ needs.changes.outputs.ui-api == 'false' }}
#        uses: ./.github/workflows/ui-api.yml

#      - name: Skip UI API build?
#        if: ${{ needs.changes.outputs.ui-api == 'false' }}
#        run: echo "No changes in ui-api, skipping build"

#  ui-app-job:
#    runs-on: ubuntu-latest
#    needs: changes

#    steps:
#      - name: Build UI API?
#        if: ${{ needs.changes.outputs.ui-app == 'true' }}
#        uses: ./.github/workflows/ui-app.yml

#      - name: Skip UI API build?
#        if: ${{ needs.changes.outputs.ui-app == 'false' }}
#        run: echo "No changes in ui-api, skipping build"

  deploy:
    runs-on: ubuntu-latest
    needs: [ui-api-job]
#    needs: [ui-api-job, ui-app-job]

    steps:
    - uses: actions/checkout@v4
    - run: ls -al
