name: parent

on:
  push:
    branches: [ "main" ]

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: ls -al

    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          ui-api:
            - 'ui/ui-api/**'
          ui-app:
            - 'ui/vite-ui-app/**'

  ui-api-build:
    uses: ./.github/workflows/ui-api.yml

  ui-app-build:
    uses: ./.github/workflows/ui-app.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [ui-api-build, ui-app-build]

    steps:
    - uses: actions/checkout@v4
    - run: ls -al
