# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: UI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ui/vite-ui-app

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/ui/vite-ui-app/package-lock.json'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls -al
    - run: npm ci
    - run: npm run build --if-present
    #- run: npm test

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ui/vite-ui-app

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/ui/vite-ui-app/package-lock.json'
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: ls -al
    - run: npm ci
    - run: npm run lint --if-present
